spring:
  datasource:
#    url: jdbc:h2:mem:testdb
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

grpc:
  server:
    port: 50051